version: "3.8"

services:
  next-app:
    container_name: angency-ui-next-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${APP_ENV}
      - API_URL=${API_URL}
    restart: unless-stopped